dist: bionic

language: cpp

before_install:
  - sudo apt-get -y install clang graphviz xdot libboost-system-dev libboost-python-dev libboost-filesystem-dev

install:
  - sudo apt-get -y install libboost-serialization-dev libboost-graph-dev libboost-dev sqlite3
  - git clone --depth=50 https://github.com/YosysHQ/yosys.git
  - pushd yosys
  - make config-gcc && make -j$(nproc) && sudo make install
  - popd
  - git clone --depth=50 https://github.com/Boolector/boolector.git
  - pushd boolector
  - ./contrib/setup-lingeling.sh
  - ./contrib/setup-btor2tools.sh
  - ./configure.sh --shared && cd build && make -j$(nproc) && sudo make install
  - popd

script:
  - mkdir build && cd build && cmake .. && make -j$(nproc)
