/* -*- c++ -*-
 *  yosys-als -- Approximate logic synthesis
 *
 *  Copyright (C) 2019  Alberto Moriconi <a.moriconi@studenti.unina.it>
 *
 *  Permission to use, copy, modify, and/or distribute this software for any
 *  purpose with or without fee is hereby granted, provided that the above
 *  copyright notice and this permission notice appear in all copies.
 *
 *  THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
 *  WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
 *  MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
 *  ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
 *  WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
 *  ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
 *  OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
 *
 */

#include "graph.h"
#include "als_worker.h"
#include "kernel/yosys.h"
#include "als_problem.h"
#include <amosa.hpp>
#include <string>
#include <vector>
#include <fstream>

/**
 * @brief @ Runs an ALS step on selected module.
 * 
 * @param module A module of the circuit to be approximate.
 */
void yosys_als::AlsWorker::run(Module *const module)
{
    // The lut-catalog is read from file
	log_header(module->design, "Loading the LUTs Catalog on file...\n");
	std::ifstream input_stream(catalog_file_name.c_str(), std::ios::binary | std::ios::in);
	if(input_stream.is_open())
		input_stream >> catalog;
	input_stream.close();

	// k-feasible cuts are computed by performing a functionally-equivalent k-lut mapping.
	// Performing 4-LUT mapping
	ScriptPass::call(module->design, "synth -lut 4");

	// For each unique k-feasible cut or, correspondingly, for each unique LUT specification a catalog of variants is
	// generated by the following loop. The generation procedure starts from the exact Boolean function specification
	// and introduces approximation increasingly, while performing the exact synthesis of variants, by making use of a 
	// SMT solver
	log_header(module->design, "Running SMT exact synthesis for LUTs...\n");
    catalog.generate_lut_variants(module, debug);

    // Storing the catalog
	log_header(module->design, "Storing the LUTs Catalog on file...\n");
	std::ofstream out_stream(catalog_file_name.c_str(), std::ios::binary | std::ios::out);
	if (out_stream.is_open())
		out_stream << catalog;
	out_stream.close();

	// Getting the graph of connected LUTs and the array of vertices in topological order
	log_header(module->design, "Getting the graph of interconnected luts...\n");
	graph_t luts_graph(module);
	
	// Defining the error-evaluator
	log_header(module->design, "Building the evaluator...\n");
	evaluator_t evaluator(luts_graph, catalog, 1000);
		
    // Optimization
	// The AIG-rewriting is formulated as a Multi-objective Optimization problem, by making use od the als_problem_t
	// class, and approximate variants are generated by substituting each instance of a given sub-AIG in the LUT-mapped
	// circuit with an element taken from the catalog, then rewriting back the corresponding AIG. The optimization
	// process is performed by the amosa::optimization_engine_t template class.
	amosa::optimization_engine_t<als_problem_t> engine(3422, 24, 0.97, 2500, 100, 30);
	als_problem_t baseline_solution(luts_graph, catalog, evaluator);
	log_header(module->design, "Setting the baseline solution for the evaluator...\n");
	evaluator.set_baseline_solution(baseline_solution.get_ax_configuration());
	
	log_header(module->design, "Running AMOSA...\n");
	engine.run(baseline_solution, 1);

    // Once the optimization process is completed, Pareto-optimal approximate variants are written in verilog files.
    // Moreover, a report-file, that provides fitness-function values for each variants, is also generated.
	std::vector<als_problem_t> archive = engine.get_pareto_front();
	log_header(module->design, "Verilog sources generation...\n");
	generate_verilog(module, archive);
	log_header(module->design, "Writing report...\n");
    generate_report(archive);
}

void yosys_als::AlsWorker::replace_lut(Yosys::Module * const module, Cell *const lut, const yosys_als::aig_model_t &aig) {
	// Vector of variables in the model
	std::array<SigSpec, 2> vars;
	vars[1].append(State::S0);
	// Get LUT ins and outs
	SigSpec lut_out;
	for (auto &conn : lut->connections())
	{
		if (lut->input(conn.first))
			vars[1].append(conn.second);
		else if (lut->output(conn.first))
			lut_out = conn.second;
	}
	// Create AND gates
	std::array<std::vector<Wire *>, 2> and_ab;
	for (size_t i = 0; i < aig.num_gates; i++)
	{
		Wire *and_a = module->addWire(NEW_ID);
		Wire *and_b = module->addWire(NEW_ID);
		Wire *and_y = module->addWire(NEW_ID);
		module->addAndGate(NEW_ID, and_a, and_b, and_y);
		and_ab[0].push_back(and_a);
		and_ab[1].push_back(and_b);
		vars[1].append(and_y);
	}
	// Negate variables
	for (auto &sig : vars[1])
	{
		Wire *not_y = module->addWire(NEW_ID);
		module->addNotGate(NEW_ID, sig, not_y);
		vars[0].append(not_y);
	}
	// Create connections
	assert(GetSize(and_ab[0]) == GetSize(and_ab[1]));
	assert(GetSize(vars[0]) == GetSize(vars[1]));
	for (int i = 0; i < GetSize(and_ab[0]); i++)
		for (int c = 0; c < GetSize(and_ab); c++)
		{
			int g_idx = aig.num_inputs + i;
			int p = aig.p[g_idx][c];
			int s = aig.s[g_idx][c];
			module->connect(and_ab[c][i], vars[p][s]);
		}
	module->connect(lut_out, vars[aig.out_p][aig.out]);
	// Delete LUT
	module->remove(lut);
}

/**
 * @brief Generate a report file, which provide the fitness-function values for each of the approximate variants
 * @param archive Archive of Pareto-optimal solutions provided by the AMOSA optimization algorithm.
 * @param string file name.
 */
void yosys_als::AlsWorker::generate_report(const std::vector<als_problem_t> &archive) const {
    std::ofstream stream(report_file_name.c_str(), std::ios::out);
    std::vector<yosys_als::als_problem_t>::const_iterator it = archive.cbegin(), end = archive.cend();
    for (unsigned i = 0; it != end; it++)
    {
        std::vector<double> ff_values;
        it->get_fitness_values(ff_values);
        std::string configuration_name = "configuration_" + std::to_string(i) + ".v";
        stream << configuration_name << "\t";
        for (std::vector<double>::const_iterator ff_it = ff_values.cbegin(); ff_it != ff_values.cend(); ff_it++)
        {
            stream << *ff_it << "\t";
        }
        stream << std::endl;
    }
    stream.close();
}

/**
 * @brief Generate a Verilog HDL source file for each Approximate configuration in the archive.
 * @param archive Archive of Pareto-optimal solutions provided by the AMOSA optimization algorithm.
 */
void yosys_als::AlsWorker::generate_verilog(Yosys::Module * const module, const std::vector<als_problem_t> &archive)
{
    std::vector<yosys_als::als_problem_t>::const_iterator it = archive.cbegin(), end = archive.cend();
    for (unsigned i = 0; it != end; it++)
    {
    	// Cloning the module, to generate a new approximate variant leaving the original model unaltered
    	Yosys::Module ax_module;
    	module->cloneInto(&ax_module);
    	for (auto &sub : it->get_ax_configuration())
	    	replace_lut(&ax_module, sub.first.cell, catalog[get_lut_param(sub.first.cell)][sub.second]);
    	
		// Generate Verilog source file for each approximate configuration
		std::string cmd_configuration_name = "write_verilog configuration_" + std::to_string(i) + ".v";
		ScriptPass::call(ax_module.design, cmd_configuration_name.c_str());
    }
}
