#include "lut_catalog.h"
#include <fstream>

USING_YOSYS_NAMESPACE


/**
 * @brief Generate the lut calalog for the considered module
 *
 * For each unique k-feasible cut or, correspondingly, for each unique LUT specification a catalog of variants is
 * generated by the following loop. The generation procedure starts from the exact Boolean function specification
 * and introduces approximation increasingly, while performing the exact synthesis of variants, by making use of a
 * SMT solver
 */
void yosys_als::lut_catalog_t::generate_lut_variants(Module *const module, bool debug) {
    for (auto cell : module->cells())
        if (yosys_als::is_lut(cell))
        {
            // Searching for entries in the catalog
            const auto &fun_spec = yosys_als::get_lut_param(cell);
            if (synthesized_luts.find(fun_spec) == synthesized_luts.end())
            {
                // If no entry is found, then synthesis is performed
                synthesized_luts[fun_spec] = std::vector<yosys_als::aig_model_t>{synthesize_lut(fun_spec, 0, debug)};
                // Also approximate logic synthesis is performed, by gradually increasing the degree of
                // approximation.
                size_t dist = 1;
                while (synthesized_luts[fun_spec].back().num_gates > 0)
                {
                    auto approximate_candidate = synthesize_lut(fun_spec, dist++, debug);
                    synthesized_luts[fun_spec].push_back(std::move(approximate_candidate));
                }
            }
        }
}


std::ofstream &yosys_als::operator<<(std::ofstream &os, const yosys_als::lut_catalog_t & cat)
{
	// Writing the amount of entries into the file
	os << cat.synthesized_luts.size(); 	// writing the actual size of the
	// For each of the element into synthesized_luts
	for (auto it : cat.synthesized_luts)
	{
		// the first field of the element (Yosys::Const) is written as a string
		std::string first = it.first.as_string();
		os << first;
		// Writing the amount of entries of the synthesized aigs
		os << it.second.size();
		// Writing the aig models
		for (auto aig_model : it.second)
			os << aig_model;
	}
	return os;
}

std::ifstream &yosys_als::operator>>(std::ifstream &is, yosys_als::lut_catalog_t & cat)
{
	size_t catalog_size;
	is >> catalog_size;
	for (size_t i = 0; i < catalog_size; i++)
	{
		std::string first;
		is >> first; // Function specification, the Yosys::Const
		size_t second_size; // Amount of aig_model_t for each key
		is >> second_size;
		std::vector<aig_model_t> vec;
		for (size_t j = 0; j < second_size; j++)
		{
			aig_model_t aig;
			is >> aig;
			vec.push_back(aig);
		}
		cat.synthesized_luts.insert(std::pair<Const, std::vector<aig_model_t>>(Const(first), vec));
	}
	return is;
}
